# Generated by Django 4.2.19 on 2025-03-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='feedimage',
            field=models.FileField(upload_to=''),
        ),
    ]
