# Generated by Django 4.2.19 on 2025-03-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evolve', '0003_contactmessage_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='offers',
        ),
    ]
