# Generated by Django 4.2.19 on 2025-03-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evolve', '0004_remove_gallery_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='quantity',
        ),
    ]
