# Generated by Django 4.2.19 on 2025-05-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolve', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_description',
            field=models.CharField(blank=True, help_text='A short description of the product (optional, max 200 characters)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='star_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Star rating from 1 to 5'),
        ),
    ]
