# Generated by Django 5.2 on 2025-05-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolve', '0005_remove_gallery_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(default='uncategorized', max_length=100),
        ),
    ]
